package app.module.analytics.model;

public enum AnalyticsEventType {
  SUBSCRIBE,
  UNSUBSCRIBE,
  BLOCK_VIEW,
  BUTTON_CLICK,
  PAYMENT_START,
  ADMIN_QUESTION_SENT,
  PAYMENT_SUCCESS,
  PAYMENT_FAILED,
  PERSONAL_DATA_SUBMIT,
  EXIT,
  BOT_ERROR;
}

